### PR TITLE
feat(client): Support providing custom WebSocket implementations

### LINKED ISSUE #16: ReferenceError: WebSocket is not defined
I've tried running the "Client usage with Apollo" example from the `README.md` under Node.

**Expected Behaviour**
* it works...

**Actual Behaviour**
```
ReferenceError: WebSocket is not defined
    at connect (.../node_modules/graphql-transport-ws/lib/client.js:126:24)
    at .../node_modules/graphql-transport-ws/lib/client.js:220:67
    at Object.createClient (.../node_modules/graphql-transport-ws/lib/client.js:244:11)
    ...
```

**Further Information**
`subscriptions-transport-ws` offers an optional `webSocketImpl` param on the client constructor (https://github.com/apollographql/subscriptions-transport-ws#constructorurl-options-websocketimpl) - any plans to do something similar?

### LINKED ISSUE #17: Support custom WebSocket implementations on the client side
Closes #16 

### Story
Sometimes you want to use the client in a non-browser environment or with an outdated browser. In order to support both worlds, the client supports passing in a custom WebSocket implementation during the setup.

### PR DESCRIPTION
**Pull request by enisdenjo**
Closes #17
Closes #16

### CODE REVIEW

**Comment by olexiyb** [comment]
Hi,
the fix is working for `createClient`, but `subscribe` function is not for jest.

```
ReferenceError: window is not defined

    at generateUUID (node_modules/graphql-transport-ws/lib/client.js:367:5)
    at Object.subscribe (node_modules/graphql-transport-ws/lib/client.js:266:26)
```

**Comment by enisdenjo** [comment]
Ah yes, I search for the Crypto module (used for generating the UUIDs) in the `window` variable, which does not exist in Node environments.

Opened an additional issue: #21

**Comment by enisdenjo** [comment]
Hey @olexiyb,

you might find the [v1.7.0 release](https://github.com/enisdenjo/graphql-transport-ws/releases/tag/v1.7.0) interesting. There is also a new recipe in the readme for "Client usage with Node".

A simplified example (without the optional `generateID` which uses Crypto) would be:

```ts
const WebSocket = require('ws'); // yarn add ws
const { createClient } = require('graphql-transport-ws');

const client = createClient({
  url: 'wss://no.browser/graphql',
  webSocketImpl: WebSocket,
});

// consider other recipes for usage inspiration
```

**Pull request merged**
